
[[dependency]]
org = "ballerinax"
name = "github"
version = "0.99.18"

[[dependency]]
org = "ballerinax"
name = "googleapis.calendar"
version = "0.1.8"

[[dependency]]
org = "ballerinax"
name = "googleapis.gmail"
version = "0.99.11"

[[dependency]]
org = "ballerinax"
name = "googleapis.sheets"
version = "0.99.11"

[[dependency]]
org = "ballerinax"
name = "googleapis.drive"
version = "0.1.5"

[[dependency]]
org = "ballerinax"
name = "googleapis.people"
version = "0.1.3"

[[dependency]]
org = "ballerinax"
name = "sfdc"
version = "2.1.11"

[[dependency]]
org = "ballerinax"
name = "slack"
version = "0.9.9"

[[dependency]]
org = "ballerinax"
name = "twilio"
version = "0.99.10"

[[dependency]]
org = "ballerinax"
name = "netsuite"
version = "0.9.7"

[[dependency]]
org = "ballerinax"
name = "azure_eventhub"
version = "0.1.5"

[[dependency]]
org = "ballerinax"
name = "azure_cosmosdb"
version = "0.1.5"

[[dependency]]
org = "ballerinax"
name = "azure_storage_service.files"
version = "0.1.1"

[[dependency]]
org = "ballerinax"
name = "azure_storage_service.blobs"
version = "0.1.1"

[[dependency]]
org = "ballerinax"
name = "mongodb"
version = "2.0.8"

[[dependency]]
org = "ballerinax"
name = "redis"
version = "0.99.7"

[[dependency]]
org = "ballerinax"
name = "aws.s3"
version = "0.99.6"

[[dependency]]
org = "ballerinax"
name = "aws.sqs"
version = "0.99.5"

[[dependency]]
org = "ballerinax"
name = "covid19"
version = "0.7.0"

[[dependency]]
org = "ballerinax"
name = "openweathermap"
version = "0.6.0"

[[dependency]]
org = "ballerinax"
name = "worldbank"
version = "0.7.0"

[[dependency]]
org = "ballerinax"
name = "zoom"
version = "0.3.0"

[[dependency]]
org = "ballerinax"
name = "spotify"
version = "0.2.0"

[[dependency]]
org = "ballerinax"
name = "sendgrid"
version = "0.2.0"

[[dependency]]
org = "ballerinax"
name = "medium"
version = "0.2.0"

[[dependency]]
org = "ballerinax"
name = "leanix.integrationapi"
version = "0.1.0"

[[dependency]]
org = "ballerinax"
name = "choreo"
version = "0.2.8"

[[dependency]]
org = "wso2"
name = "choreo.sendemail"
version = "0.3.0"

[[dependency]]
org = "wso2"
name = "choreo.sendsms"
version = "0.3.0"

[[dependency]]
org = "wso2"
name = "choreo.sendwhatsapp"
version = "0.3.0"
