name: Clone Template
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # checkout source repo
      - name: Checkout
        uses: actions/checkout@v2
        with:
          path: source

      # checkout template repo
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: choreo-templates/service
          path: template

      # Runs a set of commands using the runners shell
      - name: Copy template files and push to the user repo
        run: |
          rm -rf $GITHUB_WORKSPACE/template/.git
          cp -a $GITHUB_WORKSPACE/template/. $GITHUB_WORKSPACE/source/.
          rm -rf template
          cd source
          sed -i -e 's/{{ .BallerinaVersion}}/1.0.1/g' Dockerfile
          # rm -rf .github/workflows/clone-template.yml
          git config user.name wso2-ipaas-bot
          git config user.email integration2020.wso2@gmail.com
          git add .
          git commit -m "initial choreo template files"
          git push
